# Numpy tutorial

In [2]:
import numpy as np

## Creating arrays

In [14]:
#single dimension array
y = np.array([12,23,45,67,89,75])
print(y)


[12 23 45 67 89 75]


In [15]:
#multiple dimension array
z = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(z)

[[1 2 3 4 5]
 [6 7 8 9 0]]


## getting properties of arrays


In [12]:
#getting dimension
print(y.ndim)



1


In [13]:
#getting shape
print(z.shape)

(2, 5)


In [11]:
#getting data type
print(z.dtype)

int32


## Accessing/changing things in array

In [16]:
rel = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#getting a specific element
rel[1,5]

13

In [18]:
#get a specific row
rel[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get a specific collumn
rel[ :,2]

array([ 3, 10])

## Other ways of creating an array

In [25]:
#All 0s array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
#All 1s array
np.ones((2,2), dtype='int32')

array([[1, 1],
       [1, 1]])

In [28]:
#other numbers
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [30]:
#using properties of another array for other numbers
np.full_like(z,12)

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [32]:
#random decimal numbers
np.random.rand(2,3)

array([[0.03706224, 0.24918013, 0.01956194],
       [0.2701309 , 0.87941109, 0.67742707]])

In [33]:
#random while copying a shape
np.random.random_sample(z.shape)

array([[0.72409803, 0.20760225, 0.20940234, 0.658511  , 0.61223913],
       [0.91801478, 0.76048466, 0.53155225, 0.28659926, 0.08483829]])

In [34]:
#random integer values(.randint(limit value, size = (size)))
np.random.randint(13, size = (3,3))

array([[ 4, 11,  6],
       [12,  7, 12],
       [ 5,  9,  5]])

In [35]:
#Identity matrix (.identity(size))
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])